---
title: "Species Portfolio (R)"
author: "Kiri Daust, Will MacKenzie"
format: html
editor: visual
---

# Setup

```{r}
library(data.table)
library(climr)
library(ccissdev)
library(sportr)
library(pool)
library(foreach)
library(scales)
library(nloptr)
library(dplyr)
library(magrittr)
library(ggplot2)
library(ggthemes)
library(ranger)

source("optimisation.R")
source("portfolio_fns.R")
```

## Create covariance matrix

```{r}
req_trees <- c("Ac", "At", "Bg", "Bl", "Bp", "Cw", "Dr", "Ep", "Fd", 
"Hm", "Hw", "Jw", "Lw", "Mb", "Pa", "Pl", "Pw", "Py", "Sb", "Ss", 
"Sx", "Yc")
#S1 <- fread("D:\\CommonTables\\TreeFeasibility\\Feasibility_v12_13_w_OHR.csv")
#sigma_feas <- make_covmat(S1, req_trees)
#sigma_feas <- make_covmat(copy(ccissdev::S1),req_trees)
sigma_feas <- fread("Feasibility_CovMat.csv")
```

## Specify Parameters

```{r}
current_unit <- "SBSdk/01" ##should lookup on map so this is automatic

##currently only setup for one point but trivial to expand
#location <- data.table(lat = 54.43161,	lon = -128.6196, elev =	163, id = 1)
location <- data.table(lat =  54.773879,	lon = -127.156558, elev =	500, id = 1)
eda <- "C4"

##mean loss parameters for feasibility (in percentages per year)
feas_prob <- data.table(Feas = c(1,2,3,4), PropLoss = c(0.1,0.5,2,5), "NoMort" = c(95,85,60,40))

##currently not using this but likely will
#change_prob <- data.table(FeasDiff = c(-3,-2,-1,0,1,2,3), PropLoss = c(0,0,0,0,1,1,1))

tree_ls <- c("Fd","Pl","Sx","At","Bl","Cw","Hw","Dr") ##what species to include
boundDat <- data.table(Spp = tree_ls) ##set bound on species - no bounds by default
boundDat[,`:=`(minWt = 0, maxWt = 1)]

```

## Get BGC Predictions

```{r}
#| cache: true

clim_dat <- get_clim(location) ##yearly climate data
```

```{r}
load("../Common_Files/BGCModel_Extratrees_Balanced.Rdata") ##load bgc model
#load("D:\\CommonTables\\MachineLearningModels\\BGCModel_Extratrees_Balanced.Rdata") ##load bgc model

bgc_ss <- prep_data(clim_dat, BGCmodel, copy(S1), copy(E1), eda) ##bgc predictions

clim_dat[,run_id := interaction(id,GCM,SSP,RUN)]
temp <- unique(bgc_ss[,.(run_id,PERIOD,BGC)])

clim_plot <- clim_dat[temp, on = c("run_id","PERIOD")]
clim_plot <- clim_plot[run_id == "1.UKESM1-0-LL.ssp245.r1i1p1f2",]

clim_plot[,PERIOD := as.numeric(PERIOD)]
ggplot(clim_plot, aes(x = PERIOD, y = DD5)) +
  geom_line() +
  geom_text(aes(label = BGC), size = 2)

ggplot(clim_plot, aes(x = PERIOD, y = PPT_JAS)) +
  geom_line() +
  geom_text(aes(label = BGC), size = 2)
```

# Run Portfolio

```{r}
portfolio <- run_portfolio(bgc_ss, ccissdev::SIBEC, copy(S1), tree_ls, feas_prob, sigma = NULL) ##sigma = NULL calculate covariance on simulations; set sigma = sigma_feas (calculated above) to use specific covariance matrix
```

## Check out the simulations

```{r}
ggplot(portfolio$Simulation, aes(x = Year, y = Returns, col = Spp)) +
  geom_smooth(method = "loess")
```

```{r}
ggplot(portfolio$Simulation, aes(x = Year, y = Returns, col = Spp, group = interaction(It, Spp))) +
  geom_line()
```

# Plot Portfolio

## Efficient Frontier

```{r}
plot_ef(portfolio$Portfolio, run_list = portfolio$run_list, current_unit = current_unit, returnValue = 0.9)
```

## Violin Plots

Actually turns out boxplots work better here

```{r}
max_sharpe <- get_portfolio(portfolio_raw = portfolio$Portfolio, run_list = portfolio$run_list, what = "Sharpe")
max_sharpe[,Stat := "MaxSharpe"]

spec_ret <- get_portfolio(portfolio_raw = portfolio$Portfolio, run_list = portfolio$run_list, what = "Return", return_value = 0.9)
spec_ret[,Stat := "Return_0.9"]

min_sd <- get_portfolio(portfolio_raw = portfolio$Portfolio, run_list = portfolio$run_list, what = "MinSd")
min_sd[,Stat := "MinRisk"]

max_sd <- get_portfolio(portfolio_raw = portfolio$Portfolio, run_list = portfolio$run_list, what = "MaxSd")
max_sd[,Stat := "MaxReturn"]

port_all <- rbind(max_sharpe, spec_ret, min_sd, max_sd)
port_all <- melt(port_all, id.vars = c("SiteNo","Stat"))

ggplot(port_all, aes(x = variable, y = value)) +
  geom_boxplot() +
  facet_wrap(~ Stat) +
  xlab("Species") +
  ylab("Weighting")
```
