# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

gs2gw <- function(x, a, b) {
    .Call(`_sportr_gs2gw`, x, a, b)
}

SimGrowth_Climate <- function(DF, cmdMin, cmdMax, tempMin, tempMax, climLoss) {
    .Call(`_sportr_SimGrowth_Climate`, DF, cmdMin, cmdMax, tempMin, tempMax, climLoss)
}

SimGrowth_Regular <- function(DF) {
    .Call(`_sportr_SimGrowth_Regular`, DF)
}

simGrowthCpp <- function(DF) {
    .Call(`_sportr_simGrowthCpp`, DF)
}

